### ISSUE TITLE
SIRI CT data

### ISSUE THREAD

**Issue by sunghangga** [BISONNL/SIRI-NL#1]
Hi @hennoit, I would to ask about SIRI CT (connecting) data. In Netex NL data, I just find data related bus vehicle and for another vehicle like rail, tram, ferry, etc. I can't find it. Do you know where I can find those data? Thank you for your time.

**Comment by hennoit** [comment]
In The Netherlands we are still working on the Dutch SIRI Profile. Here on github you will only find the xsd for our subset of SIRI-PT, which was done 2 years ago. In the final Dutch SIRI Profile this may still change, and additionally there will be a subset of SIRI-ET, SIRI-VM and SIRI-SX. We do not expect to include SIRI-CT in our Profile at this moment.

Because there is not yet a Dutch SIRI Profile, you probably will not be able to find actual SIRI data ("real time") from The Netherlands - at least not on the official portals. But there is already NeTEx data ("long term planning") available from some operators. Look on one of the official portals, e.g. www.ndovloket.nl. 

This is mostly bus data, I think, but there is some tram (and ferry?) information too in these publications. Try GVB, RET or HTM.
The Dutch Railways do not yet publish NeTEx data, so not much rail data, I am afraid. Perhaps a few in the publications by Arriva and Keolis.

**Comment by sunghangga** [comment]
Thank you for your information, really helped me

**Comment by sunghangga** [comment]
Is it right that SIRI data can be retrieved from NETEX data? or SIRI data has another data source? Like GTFS has data source for GTFS and GTFS-Realtime has another data source for GTFS-Realtime which two are different data source

**Comment by hennoit** [comment]
In many cases operators indeed will have different systems for long term planning (NeTEx) and real time data (SIRI), but that is not a requirement. The standards (and also the Dutch Profile) do expect that the two publications are closely related to each other - which means that the same identifiers are used for (important) objects like Line, ScheduledStopPoint, etc. 
This is also important because SIRI relies on NeTEx for many details of the PT network. For example, a lot of information about stops (location etc.) cannot be communicated in SIRI, so the client will have to look that up in the NeTEx publication using the stop identifier from the SIRI message.

**Comment by sunghangga** [comment]
Oh fine, do you know the components that make up SIRI data other than NETEX data? which can create realtime SIRI. Thank you.

**Comment by hennoit** [comment]
You will have to look into the SIRI xsd for that... I don't have a quick list available, sorry.

**Comment by sunghangga** [comment]
Yeah, sure. Thank you for your explanation, really helped me.
